import { Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

import { Encode_Sans } from "next/font/google";

const encodeSans = Encode_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${encodeSans.variable} antialiased`}
          className={`${encodeSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
